# -*- coding: utf-8 -*-
"""sales_analysis (3).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rbwAdgB5rKlhgPePVqzMMQaRaFnrOqyT
"""

print("Hello, Data Analyst!")

price = 2.5
quantity = 10
print(price * quantity)

products = ["Milk", "Bread", "Eggs"]
prices = [2.5, 1.5, 3.0]

print(products)
print(prices)

import pandas as pd

data = {
    "Product": ["Milk", "Bread", "Eggs"],
    "Price": [2.5, 1.5, 3.0],
    "Quantity": [10, 20, 15]
}

df = pd.DataFrame(data)

print(df)

df["Total_Sales"] = df["Price"] * df["Quantity"]

print(df)

import pandas as pd

data = {
    "Product": ["Milk", "Bread", "Eggs"],
    "Price": [2.5, 1.5, 3.0],
    "Quantity": [10, 20, 15]
}

df = pd.DataFrame(data)

print(df)

df["Total_Sales"] = df["Price"] * df["Quantity"]

print(df)

df[df["Product"] == "Milk"]

df[df["Total_Sales"] >= 30]

df[df["Quantity"] > 15]

df[(df["Total_Sales"] >20) & (df["Price"] < 3)]

print(df.columns)

df.groupby("Product")["Total_Sales"].sum()

df.groupby("Product", as_index=False)["Total_Sales"].sum()

df.groupby("Price")["Total_Sales"].sum()

df.groupby("Product").agg({
    "Total_Sales": "sum",
    "Quantity": "mean"
})

df.groupby("Product")["Quantity"].sum()

import pandas as pd
import matplotlib.pyplot as plt

data = {
    "Product": ["Milk", "Bread", "Eggs"],
    "Price": [2.5, 1.5, 3.0],
    "Quantity": [10, 20, 15]
}

df = pd.DataFrame(data)
df["Total_Sales"] = df["Price"] * df["Quantity"]

sales_by_product = df.groupby("Product", as_index=False)["Total_Sales"].sum()

df.groupby("Product", as_index=False)["Total_Sales"].sum().sort_values("Total_Sales", ascending=False)

df.groupby("Product", as_index=False)["Total_Sales"].sum() \
  .sort_values("Total_Sales", ascending=True)

plt.figure()

plt.bar(sales_by_product["Product"], sales_by_product["Total_Sales"])

plt.title("Total Sales by Product")
plt.xlabel("Product")
plt.ylabel("Total Sales")

plt.show()

plt.figure()
plt.bar(df["Product"], df["Quantity"])

plt.title("Quantity Sold by Product")
plt.xlabel("Product")
plt.ylabel("Quantity")

plt.show()

plt.tight_layout()

df[(df["Price"] > 2) & (df["Quantity"] > 10)]





df[df["Total_Sales"] > 30]