# -*- coding: utf-8 -*-
"""sales_analysis.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZAe6fRJXxiXRnK3pcz6ZcCvxTuVoBtc8
"""

import pandas as pd
import matplotlib.pyplot as plt

def create_data():
    data = {
        "Product": ["Milk", "Bread", "Eggs"],
        "Price": [2.5, 1.5, 3.0],
        "Quantity": [10, 20, 15]
    }
    return pd.DataFrame(data)

def calculate_total_sales(df):
    df["Total_Sales"] = df["Price"] * df["Quantity"]
    return df

def total_sales_by_product(df):
    return df.groupby("Product")["Total_Sales"].sum()

def main():
    df = create_data()
    df = calculate_total_sales(df)

    print(df)
    print(total_sales_by_product(df))

if __name__ == "__main__":
    main()